### ISSUE TITLE
Hook into the XIVSync API to automatically add characters which aren't currently tracked on the XIVDB API

### ISSUE THREAD

**Issue by JamesDonnelly** [ApkalluFalls/.com-feedback#17]
A conversation on the XIVDB Discord server yesterday:

> Premium Virtue: If people submit you issues, and you find them on lodestone you could add them via: https://xivsync.com/character/add/730968
Premium Virtue: then just tell them to skip XIVDB
Premium Virtue: if it's on lodestone it should work however
Premium Virtue: Depends how basic their name is, someone named "la la" likely wont be found easily lol no paging
Premium Virtue: It sounds like some might just be entering it on your site and hoping for the best
Premium Virtue: but they're not on XIVDB.
Premium Virtue: You could query xivsync and then tell them they were not found and to try again in 5 mins lol
Premium Virtue: auto-populate my site :smile:
Tequila Mockingbird: I've edited my comment and I'll just link people to that from now on: https://www.reddit.com/r/ffxiv/comments/6a5yoc/ive_created_an_achievement_minion_and_mount/dhbzqvl/
Premium Virtue: would be slow queries though as Sync is in japan.

**Comment by vekien** [comment]
Some more for you on this:

You can live search Lodestone via: 
- https://xivsync.com/character/search?name=Premium+Virtue&server=Phoenix

You can add a character to XIVSync Tracking via: 
- https://xivsync.com/character/add/730968

> It is safe to add a character that already exists, adding simply puts it into a queue (ID/TimeAdded), the system wont re-add a character.

You can request a force update via: 
- https://xivsync.com/character/update/730968

Requesting update simply places them to the front of the queue and they will update in the next couple minutes. I update roughly 1300 characters a minute so should be fine to allow people to freely do this.

**Some pseudo logic you could create:**

- If character not found on XIVDB:
  - Search Lodestone, if found on Lodestone:
    - Request xivsync `/character/add/{id}` - inform user to try again in 5 minutes. Could run them through making achievements public and checking the status on that.
    - else; show some error

**Info on XIVDB's Syncing process:**

A cronjob on XIVSync runs every minute adding characters. XIVDB has a cronjob running every 2 minutes on to sync the data. So once a character "add" request is called, it will be on XIVDB and ready within the next couple minutes. XIVDB character information is cached

**Pre-empt checking**

It is possible to check if a characters achievements are public or not without XIVDB:

- https://xivsync.com/character/parse/730968/achievements?kind=1

This would be empty if they're private.

---

Will leave you with that, quite a lot of routes and stuff you can do :)

**Comment by JamesDonnelly** [comment]
That's a great amount of info, especially the part about pre-determining if a character's achievements are private - that'd be a really nifty validation check. Thanks a lot!

**Comment by JamesDonnelly** [comment]
From XIVDB's Discord:

> Premium Virtue: @Tequila Mockingbird i made a thing for people to add chars without having to go through account process http://xivdb.com/character/add which makes it easier for apps like yours

This will mean that instead of directly hooking into the XIVSync API the app can simply redirect to XIVDB if needed.
