### ISSUE TITLE
"No characters were found with this name on {world}. Please try again." is too obscure

### ISSUE THREAD

**Issue by JamesDonnelly** [ApkalluFalls/.com-feedback#2]
This seems to be a recurring issue which is caused by XIVDB not having a reference to that character in their database. The issue is simply for them to add their character to XIVDB. The text therefore should ideally be changed to reflect this.

**Comment by Gergzilla** [comment]
Yea. As a side note I had a lot of trouble when I first setup my character sync in XIVDB.  a surefire way to get this to work (that may be worth noting in your error or help page) is for the person to use their actual Lodestone ID like http://na.finalfantasyxiv.com/lodestone/character/######  I know this isn't your issue but its good info ;)

**Comment by JamesDonnelly** [comment]
I'm closing this as the solution to #17 will no doubt render this issue moot.
