### ISSUE TITLE
Clicking on left sidebar doesn't seem to work

### ISSUE THREAD

**Issue by citrouille** [ApkalluFalls/.com-feedback#23]
It seems that after today's update, clicking on either Minions or Mounts in the left sidebar doesn't seem to work any more for me. I've tried clearing the cache but that doesn't seem to have fixed the issue. I use Firefox 52.

**Comment by JamesDonnelly** [comment]
Ah, thank you very much for reporting this. I should have this fixed shortly.

**Comment by JamesDonnelly** [comment]
This is now resolved.
