### ISSUE TITLE
The method for obtaining the Wind-up Echidna minion should be attributed to HW and not ARR

### ISSUE THREAD

**Issue by JamesDonnelly** [ApkalluFalls/.com-feedback#32]
From @SirVG on Twitter: https://twitter.com/SirVG/status/873306266726268928

**Comment by nazdir** [comment]
Just submitted the same thing.  I closed it.  Sorry.  Don't hit me.

**Comment by JamesDonnelly** [comment]
This will be pushed live on the next update.
