### ISSUE TITLE
"Reaping Stormblood" and "Mining Stormblood" switched

### ISSUE THREAD

**Issue by Neraud** [ApkalluFalls/.com-feedback#36]
It looks like those achievements have been switched in the [Gathering](https://apkallufalls.com/#/achievements/gathering) section.

[Reaping Stormblood](http://xivdb.com/achievement/1856/reaping+stormblood) is listed under Miner, and [Mining Stormblood](http://xivdb.com/achievement/1857/mining+stormblood) under Botanist.

**Comment by JamesDonnelly** [comment]
Is the in-game bug fixed? If not those achievements are actually correct.

**Comment by Neraud** [comment]
I didn't know there was an in-game bug.
I've just checked, and it is properly categorized in-game.

**Comment by JamesDonnelly** [comment]
That's interesting. These achievements were previously named incorrectly in-game: the Miner one increased when gathering items as a Botanist and the Botany one increased when gathering items as a Miner. I'll verify this myself later, thanks for the report. :)

**Comment by Neraud** [comment]
Oh, I didn't check for that.
I've only checked that the miner one was in the miner category, not that it properly increases when you mine.
So there might still be a bug in-game then. I'll try to check that tonight.
